import { api } from "../api.js";
import { escapeHtml } from "../dom.js";

const esc = (value) => escapeHtml(String(value ?? ""));
const DAYS = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"];
const scheduleState = {
  organizationId: null, weekStart: null, branches: [], users: [], roles: [], memberships: [],
  selectedBranchIds: new Set(), selectedUserIds: new Set(), shifts: new Map(), selectedCells: new Set(),
  selectionMode: false, copiedShift: null, search: "", showInactive: false,
};

function dateValue(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function dateFromValue(value) { const [year, month, day] = String(value).split("-").map(Number); return new Date(year, month - 1, day); }
function monday(date = new Date()) { const result = new Date(date.getFullYear(), date.getMonth(), date.getDate()); result.setDate(result.getDate() - ((result.getDay() + 6) % 7)); return result; }
function addDays(date, days) { const result = new Date(date); result.setDate(result.getDate() + days); return result; }
function shiftKey(employeeId, date) { return `${employeeId}:${date}`; }
function weekDays() { return Array.from({ length: 7 }, (_, index) => addDays(scheduleState.weekStart, index)); }
function dateLabel(date) { return date.toLocaleDateString("ru-RU", { day: "numeric", month: "long" }); }
function weekTitle() { const days = weekDays(); return `${days[0].getDate()}–${days[6].toLocaleDateString("ru-RU", { day: "numeric", month: "long", year: "numeric" })}`; }
function fullName(user) { return [user.last_name, user.first_name, user.middle_name].filter(Boolean).join(" ") || user.name || `Сотрудник #${user.id}`; }
function initials(user) { return fullName(user).split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function roleName(user) { const ids = scheduleState.memberships.filter((item) => String(item.user_id) === String(user.id)).map((item) => String(item.role_id)); return scheduleState.roles.find((role) => ids.includes(String(role.id)))?.name || user.position || ""; }
function userBranchIds(user) { return new Set(scheduleState.memberships.filter((item) => String(item.user_id) === String(user.id)).map((item) => String(item.branch_id)).filter(Boolean)); }
function availableUsers() {
  const branches = scheduleState.selectedBranchIds;
  const query = scheduleState.search.trim().toLocaleLowerCase("ru-RU");
  return scheduleState.users.filter((user) => {
    if (!scheduleState.showInactive && user.is_active === false) return false;
    const userBranches = userBranchIds(user);
    if (branches.size && ![...userBranches].some((id) => branches.has(id))) return false;
    if (scheduleState.selectedUserIds.size && !scheduleState.selectedUserIds.has(String(user.id))) return false;
    return !query || fullName(user).toLocaleLowerCase("ru-RU").includes(query);
  });
}
function selectedSummary(items, ids, all) { if (!items.length) return "Нет данных"; if (ids.size === items.length || all) return `Все ${items === scheduleState.branches ? "филиалы" : "сотрудники"}`; if (!ids.size) return "Не выбрано"; if (ids.size === 1) return items.find((item) => ids.has(String(item.id)))?.name || fullName(items.find((item) => ids.has(String(item.id)))); return `Выбрано: ${ids.size}`; }
function filterMarkup(type, label, items, selectedIds) {
  const allSelected = selectedIds.size === items.length;
  return `<label class="schedule-filter"><span>${label}</span><details class="branch-multiselect-dropdown" data-schedule-filter="${type}"><summary><span data-schedule-filter-summary="${type}">${esc(selectedSummary(items, selectedIds, allSelected))}</span></summary><div class="branch-multiselect-options"><label class="checkbox"><input type="checkbox" data-schedule-filter-all="${type}" ${allSelected ? "checked" : ""}>Все ${type === "branch" ? "филиалы" : "сотрудники"}</label>${items.map((item) => `<label class="checkbox"><input type="checkbox" value="${Number(item.id)}" data-schedule-filter-option="${type}" ${selectedIds.has(String(item.id)) ? "checked" : ""}>${esc(type === "branch" ? item.name : fullName(item))}</label>`).join("")}</div></details></label>`;
}
function scheduleFilters() { return `<div class="schedule-toolbar"><div class="schedule-toolbar-left">${filterMarkup("branch", "Филиал", scheduleState.branches, scheduleState.selectedBranchIds)}${filterMarkup("user", "Сотрудники", scheduleState.users.filter((user) => scheduleState.showInactive || user.is_active !== false), scheduleState.selectedUserIds)}<label class="schedule-search"><span>Поиск сотрудника</span><input type="search" data-schedule-search value="${esc(scheduleState.search)}" placeholder="Имя..."></label><label class="checkbox schedule-inactive"><input type="checkbox" data-schedule-show-inactive ${scheduleState.showInactive ? "checked" : ""}>Показывать неактивных</label></div><div class="schedule-toolbar-right"><button class="btn btn-outline-secondary" type="button" data-schedule-selection-toggle>${scheduleState.selectionMode ? "Готово" : "Выбрать несколько"}</button><button class="primary" type="button" data-schedule-create>+ Создать смену</button></div></div>`; }
function shiftTooltip(shift) { return `${shift.start_time}–${shift.end_time}${shift.breaks?.length ? ` · Перерыв ${shift.breaks.map((item) => `${item.start_time}–${item.end_time}`).join(", ")}` : ""}`; }
function scheduleCell(user, date) {
  const value = dateValue(date); const key = shiftKey(user.id, value); const shift = scheduleState.shifts.get(key); const today = value === dateValue(new Date());
  const selected = scheduleState.selectedCells.has(key);
  return `<div class="schedule-cell ${shift ? "" : "is-empty"} ${today ? "is-today" : ""} ${selected ? "is-selected" : ""}" data-schedule-cell data-user-id="${Number(user.id)}" data-date="${value}" role="button" tabindex="0" title="${shift ? esc(shiftTooltip(shift)) : "Добавить смену"}">${shift ? `<div class="schedule-shift-card"><span class="schedule-shift-time">${esc(shift.start_time)}–${esc(shift.end_time)}</span>${shift.breaks?.length ? `<span class="schedule-shift-break">${shift.breaks.length === 1 ? `${esc(shift.breaks[0].start_time)}–${esc(shift.breaks[0].end_time)}` : `${shift.breaks.length} перерыва`}</span>` : ""}</div>` : `<span class="schedule-cell-add">${scheduleState.copiedShift ? "Вставить" : "+"}</span><span>—</span>`}</div>`;
}
function employeeHead(user) { const photo = user.photo_url || (user.photo_file_id ? `/users-access/users/${Number(user.id)}/photo` : ""); return `<div class="schedule-employee-head"><span class="schedule-avatar">${photo ? `<img src="${esc(photo)}" alt="">` : esc(initials(user))}</span><span class="schedule-employee-text"><strong>${esc(fullName(user))}</strong>${roleName(user) ? `<small>${esc(roleName(user))}</small>` : ""}</span><button type="button" class="ghost schedule-week-menu" data-schedule-week-user="${Number(user.id)}" title="Действия на неделю">•••</button></div>`; }
function scheduleGrid() {
  const users = availableUsers(); const days = weekDays(); const today = dateValue(new Date());
  if (!users.length) return `<p class="empty">${scheduleState.users.length ? "Нет сотрудников по выбранным фильтрам." : "Сотрудники не найдены."}</p>`;
  return `<div class="schedule-grid-viewport"><div class="schedule-grid" data-schedule-grid><div class="schedule-day-head schedule-grid-corner">Сотрудник</div>${days.map((date, index) => `<div class="schedule-day-head ${dateValue(date) === today ? "is-today" : ""} ${index > 4 ? "is-weekend" : ""}"><strong>${DAYS[index]} ${date.getDate()}</strong>${dateValue(date) === today ? "<small>Сегодня</small>" : ""}</div>`).join("")}${users.map((user) => `${employeeHead(user)}${days.map((date) => scheduleCell(user, date)).join("")}`).join("")}</div></div>`;
}
function summary() { const days = new Set(); const users = new Set(); weekDays().forEach((date) => scheduleState.users.forEach((user) => { if (scheduleState.shifts.has(shiftKey(user.id, dateValue(date)))) { days.add(shiftKey(user.id, dateValue(date))); users.add(user.id); } })); return `Смен: ${days.size} · Сотрудников со сменами: ${users.size}`; }
function selectionBar() { if (!scheduleState.selectedCells.size) return ""; return `<div class="schedule-selection-bar">Выбрано: ${scheduleState.selectedCells.size}<button type="button" class="btn btn-outline-secondary" data-schedule-bulk>Назначить смену</button><button type="button" class="btn btn-outline-secondary" data-schedule-clear>Очистить смены</button><button type="button" class="ghost" data-schedule-unselect>Снять выбор</button></div>`; }
function pageMarkup() { return `<section class="panel schedule-page" data-schedules><div class="schedule-head"><h2>Графики</h2><div class="schedule-week-nav"><button type="button" class="ghost" data-schedule-week="prev" aria-label="Предыдущая неделя">←</button><strong class="schedule-week-title">${esc(weekTitle())}</strong><button type="button" class="ghost" data-schedule-week="next" aria-label="Следующая неделя">→</button><button type="button" class="btn btn-outline-secondary" data-schedule-today>Сегодня</button></div></div>${scheduleFilters()}<div class="schedule-actions"><button type="button" class="btn btn-outline-secondary" data-schedule-copy-week>Скопировать неделю</button><small>${esc(summary())}</small></div><div data-schedule-grid-area>${scheduleGrid()}</div>${selectionBar()}</section>`; }
export async function schedules(ctx) {
  if (String(scheduleState.organizationId || "") !== String(ctx.org.id)) {
    const [branches, users, roles, memberships] = await Promise.all([api.branches(ctx.org.id), api.users(ctx.org.id, 500), api.roles(ctx.org.id), api.branchMemberships(ctx.org.id)]);
    Object.assign(scheduleState, { organizationId: ctx.org.id, weekStart: monday(), branches, users, roles, memberships, selectedBranchIds: new Set(branches.map((item) => String(item.id))), selectedUserIds: new Set(users.filter((user) => user.is_active !== false).map((user) => String(user.id))), shifts: new Map(), selectedCells: new Set(), selectionMode: false, copiedShift: null, search: "", showInactive: false });
  }
  return pageMarkup();
}
function putModal(root, html) { root.querySelector("[data-schedule-modal]")?.remove(); root.insertAdjacentHTML("beforeend", html); }
function modal(title, body) { return `<div class="modal-backdrop" data-schedule-modal><div class="modal-card schedule-modal-card" role="dialog"><button type="button" class="modal-close" data-schedule-close aria-label="Закрыть">×</button><h3>${esc(title)}</h3>${body}</div></div>`; }
function breaksMarkup(breaks = []) { return `<div class="schedule-breaks" data-schedule-breaks>${breaks.map((item, index) => `<div class="schedule-break-row"><input type="time" data-break-start value="${esc(item.start_time)}"><span>—</span><input type="time" data-break-end value="${esc(item.end_time)}"><button type="button" class="ghost" data-schedule-remove-break="${index}">×</button></div>`).join("")}</div>`; }
function shiftForm({ title, user, date, shift, bulk = false, keys = [] }) { const value = shift || { start_time: "10:00", end_time: "19:00", breaks: [] }; return modal(title, `<form class="schedule-shift-form" data-schedule-shift-form data-user-id="${user ? Number(user.id) : ""}" data-date="${date || ""}" data-bulk="${bulk ? "true" : "false"}" data-keys="${esc(JSON.stringify(keys))}">${user ? `<p><strong>Сотрудник:</strong> ${esc(fullName(user))}<br><strong>Дата:</strong> ${esc(dateLabel(dateFromValue(date)))}</p>` : `<p>Выбрано: ${keys.length} ячеек</p>`}<div class="schedule-time-row"><label><span>Начало</span><input type="time" name="start_time" value="${esc(value.start_time)}" required></label><span>—</span><label><span>Окончание</span><input type="time" name="end_time" value="${esc(value.end_time)}" required></label></div><div><strong>Перерывы</strong>${breaksMarkup(value.breaks)}<button type="button" class="ghost" data-schedule-add-break>+ Добавить перерыв</button></div><p data-schedule-form-message></p><div class="schedule-modal-actions">${shift && !bulk ? `<button type="button" class="ghost" data-schedule-copy="${Number(user.id)}:${date}">Копировать</button><button type="button" class="client-delete-button" data-schedule-delete="${Number(user.id)}:${date}">Удалить смену</button>` : ""}<button class="primary" type="submit">${bulk ? "Применить" : "Сохранить"}</button></div></form>`); }
function openShiftModal(root, userId, date) { const user = scheduleState.users.find((item) => String(item.id) === String(userId)); const shift = scheduleState.shifts.get(shiftKey(userId, date)); putModal(root, shiftForm({ title: shift ? "Редактирование смены" : "Добавить смену", user, date, shift })); }
function validateShift(value) { if (!value.start_time || !value.end_time || value.start_time >= value.end_time) return "Время окончания должно быть позже времени начала."; const breaks = [...value.breaks].sort((a, b) => a.start_time.localeCompare(b.start_time)); for (let index = 0; index < breaks.length; index += 1) { const item = breaks[index]; if (!item.start_time || !item.end_time || item.start_time >= item.end_time || item.start_time < value.start_time || item.end_time > value.end_time) return "Перерыв должен находиться внутри смены и иметь корректное время."; if (index && item.start_time < breaks[index - 1].end_time) return "Перерывы не должны пересекаться."; } return ""; }
function refresh(root) { const page = root.querySelector("[data-schedules]"); if (page) page.outerHTML = pageMarkup(); }
function formValue(form) { return { start_time: new FormData(form).get("start_time"), end_time: new FormData(form).get("end_time"), breaks: [...form.querySelectorAll(".schedule-break-row")].map((row) => ({ start_time: row.querySelector("[data-break-start]").value, end_time: row.querySelector("[data-break-end]").value })) }; }
function applyShift(key, value, branchId) { const [employeeId, date] = key.split(":"); scheduleState.shifts.set(key, { id: `frontend-${Date.now()}-${key}`, employee_id: Number(employeeId), branch_id: Number(branchId) || 0, date, ...value, breaks: value.breaks.map((item) => ({ ...item })) }); }
export function bindSchedules(root, ctx) {
  root.addEventListener("click", (event) => {
    if (!event.target.closest("[data-schedules], [data-schedule-modal]")) return;
    if (event.target.matches("[data-schedule-modal]") || event.target.closest("[data-schedule-close]")) { root.querySelector("[data-schedule-modal]")?.remove(); return; }
    const week = event.target.closest("[data-schedule-week]"); if (week) { scheduleState.weekStart = addDays(scheduleState.weekStart, week.dataset.scheduleWeek === "next" ? 7 : -7); refresh(root); return; }
    if (event.target.closest("[data-schedule-today]")) { scheduleState.weekStart = monday(); refresh(root); return; }
    if (event.target.closest("[data-schedule-create]")) { const user = availableUsers()[0]; if (user) openShiftModal(root, user.id, dateValue(scheduleState.weekStart)); return; }
    const toggle = event.target.closest("[data-schedule-selection-toggle]"); if (toggle) { scheduleState.selectionMode = !scheduleState.selectionMode; if (!scheduleState.selectionMode) scheduleState.selectedCells.clear(); refresh(root); return; }
    const cell = event.target.closest("[data-schedule-cell]"); if (cell) { const key = shiftKey(cell.dataset.userId, cell.dataset.date); if (scheduleState.selectionMode) { scheduleState.selectedCells.has(key) ? scheduleState.selectedCells.delete(key) : scheduleState.selectedCells.add(key); refresh(root); } else if (event.ctrlKey && scheduleState.copiedShift && !scheduleState.shifts.has(key)) { applyShift(key, scheduleState.copiedShift, scheduleState.copiedShift.branch_id); refresh(root); } else openShiftModal(root, cell.dataset.userId, cell.dataset.date); return; }
    if (event.target.closest("[data-schedule-unselect]")) { scheduleState.selectedCells.clear(); refresh(root); return; }
    if (event.target.closest("[data-schedule-clear]")) { if (confirm("Удалить смены в выбранных датах?")) { scheduleState.selectedCells.forEach((key) => scheduleState.shifts.delete(key)); scheduleState.selectedCells.clear(); refresh(root); } return; }
    if (event.target.closest("[data-schedule-bulk]")) { putModal(root, shiftForm({ title: "Назначить смену", bulk: true, keys: [...scheduleState.selectedCells] })); return; }
    const removeBreak = event.target.closest("[data-schedule-remove-break]"); if (removeBreak) { removeBreak.closest(".schedule-break-row")?.remove(); return; }
    if (event.target.closest("[data-schedule-add-break]")) { event.target.closest("form").querySelector("[data-schedule-breaks]").insertAdjacentHTML("beforeend", `<div class="schedule-break-row"><input type="time" data-break-start value="13:00"><span>—</span><input type="time" data-break-end value="14:00"><button type="button" class="ghost" data-schedule-remove-break>×</button></div>`); return; }
    const copy = event.target.closest("[data-schedule-copy]"); if (copy) { scheduleState.copiedShift = scheduleState.shifts.get(copy.dataset.scheduleCopy); root.querySelector("[data-schedule-modal]")?.remove(); return; }
    const deletion = event.target.closest("[data-schedule-delete]"); if (deletion) { const [, date] = deletion.dataset.scheduleDelete.split(":"); if (confirm(`Удалить смену сотрудника на ${dateLabel(dateFromValue(date))}?`)) { scheduleState.shifts.delete(deletion.dataset.scheduleDelete); root.querySelector("[data-schedule-modal]")?.remove(); refresh(root); } return; }
    const weekUser = event.target.closest("[data-schedule-week-user]"); if (weekUser) { const keys = weekDays().map((date) => shiftKey(weekUser.dataset.scheduleWeekUser, dateValue(date))); putModal(root, shiftForm({ title: "Назначить смену на неделю", bulk: true, keys })); return; }
    if (event.target.closest("[data-schedule-copy-week]")) { const target = addDays(scheduleState.weekStart, 7); const keys = []; weekDays().forEach((date) => scheduleState.users.forEach((user) => { const source = scheduleState.shifts.get(shiftKey(user.id, dateValue(date))); if (source) keys.push({ key: shiftKey(user.id, dateValue(addDays(date, 7))), shift: source }); })); if (keys.length && (!keys.some(({ key }) => scheduleState.shifts.has(key)) || confirm("В выбранной неделе уже есть смены. Перезаписать существующие?"))) { keys.forEach(({ key, shift }) => applyShift(key, shift, shift.branch_id)); scheduleState.weekStart = target; refresh(root); } return; }
  });
  root.addEventListener("change", (event) => {
    const option = event.target.closest("[data-schedule-filter-option]"); const all = event.target.closest("[data-schedule-filter-all]");
    if (option || all) { const type = (option || all).dataset.scheduleFilterOption || (option || all).dataset.scheduleFilterAll; const items = type === "branch" ? scheduleState.branches : scheduleState.users.filter((user) => scheduleState.showInactive || user.is_active !== false); const selected = type === "branch" ? scheduleState.selectedBranchIds : scheduleState.selectedUserIds; if (all) { selected.clear(); if (all.checked) items.forEach((item) => selected.add(String(item.id))); } else { option.checked ? selected.add(String(option.value)) : selected.delete(String(option.value)); } if (type === "branch") { const visible = availableUsers().map((user) => String(user.id)); scheduleState.selectedUserIds = new Set([...scheduleState.selectedUserIds].filter((id) => visible.includes(id))); } refresh(root); return; }
    if (event.target.matches("[data-schedule-show-inactive]")) { scheduleState.showInactive = event.target.checked; if (scheduleState.showInactive) scheduleState.users.forEach((user) => scheduleState.selectedUserIds.add(String(user.id))); refresh(root); }
  });
  root.addEventListener("input", (event) => { if (event.target.matches("[data-schedule-search]")) { scheduleState.search = event.target.value; root.querySelector("[data-schedule-grid-area]").innerHTML = scheduleGrid(); } });
  root.addEventListener("submit", (event) => { const form = event.target; if (!form.matches("[data-schedule-shift-form]")) return; event.preventDefault(); const value = formValue(form); const error = validateShift(value); const message = form.querySelector("[data-schedule-form-message]"); if (error) { message.textContent = error; return; } const keys = form.dataset.bulk === "true" ? JSON.parse(form.dataset.keys || "[]") : [shiftKey(form.dataset.userId, form.dataset.date)]; const existing = keys.filter((key) => scheduleState.shifts.has(key)).length; if (form.dataset.bulk === "true" && existing && !confirm(`В выбранных ячейках уже есть ${existing} смены. Заменить их?`)) return; const branchId = [...scheduleState.selectedBranchIds][0] || 0; keys.forEach((key) => applyShift(key, value, branchId)); scheduleState.selectedCells.clear(); root.querySelector("[data-schedule-modal]")?.remove(); refresh(root); });
}
