import { api } from "../api.js";
import { escapeHtml } from "../dom.js";

const esc = (value) => escapeHtml(String(value ?? ""));
const DAYS = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"];
const scheduleState = {
  organizationId: null, weekStart: null, branches: [], users: [], roles: [], memberships: [],
  selectedBranchIds: new Set(), selectedUserIds: new Set(), shifts: new Map(), selectedCells: new Set(),
  selectionMode: false, dragSelection: { active: false, moved: false, mode: "add", startKey: null, startCell: null, visited: new Set(), suppressClick: false }, fillDrag: { active: false, sourceKey: null, sourceUserId: null, sourceDate: null, sourceShift: null, sourceUserIndex: null, sourceDateIndex: null, targetUserId: null, targetUserIndex: null, targetDate: null, targetDateIndex: null, previewKeys: new Set(), suppressClick: false }, copiedShift: null, search: "", showInactive: false,
};

function dateValue(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function dateFromValue(value) { const [year, month, day] = String(value).split("-").map(Number); return new Date(year, month - 1, day); }
function monday(date = new Date()) { const result = new Date(date.getFullYear(), date.getMonth(), date.getDate()); result.setDate(result.getDate() - ((result.getDay() + 6) % 7)); return result; }
function addDays(date, days) { const result = new Date(date); result.setDate(result.getDate() + days); return result; }
function shiftKey(employeeId, date) { return `${employeeId}:${date}`; }
function weekDays() { return Array.from({ length: 7 }, (_, index) => addDays(scheduleState.weekStart, index)); }
function dateLabel(date) { return date.toLocaleDateString("ru-RU", { day: "numeric", month: "long" }); }
function weekTitle() { const days = weekDays(); return `${days[0].getDate()}–${days[6].toLocaleDateString("ru-RU", { day: "numeric", month: "long", year: "numeric" })}`; }
function fullName(user) { return [user.last_name, user.first_name, user.middle_name].filter(Boolean).join(" ") || user.name || `Сотрудник #${user.id}`; }
function initials(user) { return fullName(user).split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function roleName(user) { const ids = scheduleState.memberships.filter((item) => String(item.user_id) === String(user.id)).map((item) => String(item.role_id)); return scheduleState.roles.find((role) => ids.includes(String(role.id)))?.name || user.position || ""; }
function userBranchIds(user) { return new Set(scheduleState.memberships.filter((item) => String(item.user_id) === String(user.id)).map((item) => String(item.branch_id)).filter(Boolean)); }
function availableUsers() {
  const branches = scheduleState.selectedBranchIds;
  const query = scheduleState.search.trim().toLocaleLowerCase("ru-RU");
  return scheduleState.users.filter((user) => {
    if (!scheduleState.showInactive && user.is_active === false) return false;
    const userBranches = userBranchIds(user);
    if (branches.size && ![...userBranches].some((id) => branches.has(id))) return false;
    if (scheduleState.selectedUserIds.size && !scheduleState.selectedUserIds.has(String(user.id))) return false;
    return !query || fullName(user).toLocaleLowerCase("ru-RU").includes(query);
  });
}
function selectedSummary(items, ids, all) { if (!items.length) return "Нет данных"; if (ids.size === items.length || all) return `Все ${items === scheduleState.branches ? "филиалы" : "сотрудники"}`; if (!ids.size) return "Не выбрано"; if (ids.size === 1) return items.find((item) => ids.has(String(item.id)))?.name || fullName(items.find((item) => ids.has(String(item.id)))); return `Выбрано: ${ids.size}`; }
function filterMarkup(type, label, items, selectedIds) {
  const allSelected = selectedIds.size === items.length;
  return `<label class="schedule-filter"><span>${label}</span><details class="branch-multiselect-dropdown" data-schedule-filter="${type}"><summary><span data-schedule-filter-summary="${type}">${esc(selectedSummary(items, selectedIds, allSelected))}</span></summary><div class="branch-multiselect-options"><label class="checkbox"><input type="checkbox" data-schedule-filter-all="${type}" ${allSelected ? "checked" : ""}>Все ${type === "branch" ? "филиалы" : "сотрудники"}</label>${items.map((item) => `<label class="checkbox"><input type="checkbox" value="${Number(item.id)}" data-schedule-filter-option="${type}" ${selectedIds.has(String(item.id)) ? "checked" : ""}>${esc(type === "branch" ? item.name : fullName(item))}</label>`).join("")}</div></details></label>`;
}
function scheduleFilters() { return `<div class="schedule-toolbar"><div class="schedule-toolbar-left">${filterMarkup("branch", "Филиал", scheduleState.branches, scheduleState.selectedBranchIds)}${filterMarkup("user", "Сотрудники", scheduleState.users.filter((user) => scheduleState.showInactive || user.is_active !== false), scheduleState.selectedUserIds)}<label class="schedule-search"><span>Поиск сотрудника</span><input type="search" data-schedule-search value="${esc(scheduleState.search)}" placeholder="Имя..."></label><label class="checkbox schedule-inactive"><input type="checkbox" data-schedule-show-inactive ${scheduleState.showInactive ? "checked" : ""}>Показывать неактивных</label></div><div class="schedule-toolbar-right"><button class="btn btn-outline-secondary" type="button" data-schedule-selection-toggle>${scheduleState.selectionMode ? "Готово" : "Выбрать несколько"}</button></div></div>`; }
function shiftTooltip(shift) { return `${shift.start_time}–${shift.end_time}${shift.breaks?.length ? ` · Перерыв ${shift.breaks.map((item) => `${item.start_time}–${item.end_time}`).join(", ")}` : ""}`; }
function scheduleCell(user, date) {
  const value = dateValue(date); const key = shiftKey(user.id, value); const shift = scheduleState.shifts.get(key); const today = value === dateValue(new Date());
  const selected = scheduleState.selectedCells.has(key);
  const fillSource = scheduleState.fillDrag.active && scheduleState.fillDrag.sourceKey === key;
  return `<div class="schedule-cell ${shift ? "" : "is-empty"} ${today ? "is-today" : ""} ${selected ? "is-selected" : ""}" data-schedule-cell data-user-id="${Number(user.id)}" data-date="${value}" role="button" tabindex="0" title="${shift ? esc(shiftTooltip(shift)) : "Добавить смену"}">${shift ? `<div class="schedule-shift-card ${fillSource ? "is-fill-source" : ""}"><span class="schedule-shift-time">${esc(shift.start_time)}–${esc(shift.end_time)}</span>${shift.breaks?.length ? `<span class="schedule-shift-break">${shift.breaks.length === 1 ? `${esc(shift.breaks[0].start_time)}–${esc(shift.breaks[0].end_time)}` : `${shift.breaks.length} перерыва`}</span>` : ""}${!scheduleState.selectionMode ? `<span class="schedule-fill-handle" data-schedule-fill-handle aria-hidden="true"></span>` : ""}</div>` : `<span class="schedule-cell-add">${scheduleState.copiedShift ? "Вставить" : "+"}</span><span>—</span>`}</div>`;
}
function employeeHead(user) { const photo = user.photo_url || (user.photo_file_id ? `/users-access/users/${Number(user.id)}/photo` : ""); return `<div class="schedule-employee-head"><div class="schedule-employee-main"><span class="schedule-avatar">${photo ? `<img src="${esc(photo)}" alt="">` : esc(initials(user))}</span><span class="schedule-employee-text"><strong>${esc(fullName(user))}</strong>${roleName(user) ? `<small>${esc(roleName(user))}</small>` : ""}</span><button type="button" class="ghost schedule-week-menu" data-schedule-week-user="${Number(user.id)}" title="Действия на неделю" aria-label="Действия на неделю">•••</button></div></div>`; }
function scheduleGrid() {
  const users = availableUsers(); const days = weekDays(); const today = dateValue(new Date());
  if (!users.length) return `<p class="empty">${scheduleState.users.length ? "Нет сотрудников по выбранным фильтрам." : "Сотрудники не найдены."}</p>`;
  return `<div class="schedule-grid-viewport"><div class="schedule-grid ${scheduleState.selectionMode ? "is-selection-mode" : ""} ${scheduleState.fillDrag.active ? "is-fill-dragging" : ""}" data-schedule-grid><div class="schedule-day-head schedule-grid-corner">Сотрудник</div>${days.map((date, index) => `<div class="schedule-day-head ${dateValue(date) === today ? "is-today" : ""} ${index > 4 ? "is-weekend" : ""}"><strong>${DAYS[index]} ${date.getDate()}</strong>${dateValue(date) === today ? "<small>Сегодня</small>" : ""}</div>`).join("")}${users.map((user) => `${employeeHead(user)}${days.map((date) => scheduleCell(user, date)).join("")}`).join("")}</div></div>`;
}
function summary() { const days = new Set(); const users = new Set(); weekDays().forEach((date) => scheduleState.users.forEach((user) => { if (scheduleState.shifts.has(shiftKey(user.id, dateValue(date)))) { days.add(shiftKey(user.id, dateValue(date))); users.add(user.id); } })); return `Смен: ${days.size} · Сотрудников со сменами: ${users.size}`; }
function selectionBar() { return `<div class="schedule-selection-bar" data-schedule-selection-bar ${scheduleState.selectedCells.size ? "" : "hidden"}><span data-schedule-selected-count>Выбрано: ${scheduleState.selectedCells.size}</span><button type="button" class="btn btn-outline-secondary" data-schedule-bulk>Назначить смену</button><button type="button" class="btn btn-outline-secondary" data-schedule-clear>Очистить смены</button><button type="button" class="ghost" data-schedule-unselect>Снять выбор</button></div>`; }
function setScheduleCellSelected(cell, selected) { cell.classList.toggle("is-selected", selected); }
function updateScheduleSelectionCount(root) { const counter = root.querySelector("[data-schedule-selected-count]"); if (counter) counter.textContent = "Выбрано: " + scheduleState.selectedCells.size; }
function syncScheduleSelectionBar(root) { const bar = root.querySelector("[data-schedule-selection-bar]"); if (!bar) return; bar.hidden = scheduleState.selectedCells.size === 0; updateScheduleSelectionCount(root); }
function resetScheduleDragSelection() { const drag = scheduleState.dragSelection; drag.active = false; drag.moved = false; drag.mode = "add"; drag.startKey = null; drag.startCell = null; drag.visited.clear(); drag.suppressClick = false; }
function resetScheduleFillDrag() { const drag = scheduleState.fillDrag; drag.active = false; drag.sourceKey = null; drag.sourceUserId = null; drag.sourceDate = null; drag.sourceShift = null; drag.sourceUserIndex = null; drag.sourceDateIndex = null; drag.targetUserId = null; drag.targetUserIndex = null; drag.targetDate = null; drag.targetDateIndex = null; drag.previewKeys.clear(); drag.suppressClick = false; }
function scheduleFillRectangle(sourceUserId, sourceDate, targetUserId, targetDate) { const users = availableUsers(); const dates = weekDays().map(dateValue); const sourceUserIndex = users.findIndex((user) => String(user.id) === String(sourceUserId)); const targetUserIndex = users.findIndex((user) => String(user.id) === String(targetUserId)); const sourceDateIndex = dates.indexOf(sourceDate); const targetDateIndex = dates.indexOf(targetDate); if ([sourceUserIndex, targetUserIndex, sourceDateIndex, targetDateIndex].some((index) => index < 0)) return []; const keys = []; for (let userIndex = Math.min(sourceUserIndex, targetUserIndex); userIndex <= Math.max(sourceUserIndex, targetUserIndex); userIndex += 1) for (let dateIndex = Math.min(sourceDateIndex, targetDateIndex); dateIndex <= Math.max(sourceDateIndex, targetDateIndex); dateIndex += 1) { const key = shiftKey(users[userIndex].id, dates[dateIndex]); if (key !== scheduleState.fillDrag.sourceKey) keys.push(key); } return keys; }
function syncScheduleFillPreview(root, keys) { const drag = scheduleState.fillDrag; drag.previewKeys.forEach((key) => root.querySelector(`[data-schedule-cell][data-user-id="${CSS.escape(String(key.split(":")[0]))}"][data-date="${CSS.escape(key.split(":").slice(1).join(":"))}"]`)?.classList.remove("is-fill-preview")); keys.forEach((key) => root.querySelector(`[data-schedule-cell][data-user-id="${CSS.escape(String(key.split(":")[0]))}"][data-date="${CSS.escape(key.split(":").slice(1).join(":"))}"]`)?.classList.add("is-fill-preview")); drag.previewKeys = new Set(keys); }
function copiedScheduleShift(shift) { return { start_time: shift.start_time, end_time: shift.end_time, breaks: (shift.breaks || []).map((item) => ({ start_time: item.start_time, end_time: item.end_time })), branch_id: shift.branch_id }; }
function applyScheduleDragCell(root, cell) { const key = shiftKey(cell.dataset.userId, cell.dataset.date); const drag = scheduleState.dragSelection; if (drag.visited.has(key)) return; if (drag.mode === "add") scheduleState.selectedCells.add(key); else scheduleState.selectedCells.delete(key); drag.visited.add(key); setScheduleCellSelected(cell, drag.mode === "add"); syncScheduleSelectionBar(root); }
function normalizeShift(item) { const date = String(item.date || item.shift_date || ""); return { ...item, employee_id: Number(item.employee_id), branch_id: Number(item.branch_id), date, start_time: String(item.start_time || "").slice(0, 5), end_time: String(item.end_time || "").slice(0, 5), breaks: (item.breaks || []).map((value) => ({ ...value, start_time: String(value.start_time || "").slice(0, 5), end_time: String(value.end_time || "").slice(0, 5) })) }; }
async function scheduleShiftMap(ctx, start = scheduleState.weekStart) { const items = await api.employeeShifts(ctx.org.id, dateValue(start), dateValue(addDays(start, 6))); return new Map(items.map((item) => { const shift = normalizeShift(item); return [shiftKey(shift.employee_id, shift.date), shift]; })); }
async function loadScheduleWeek(ctx) { scheduleState.shifts = await scheduleShiftMap(ctx); scheduleState.selectedCells.clear(); resetScheduleDragSelection(); resetScheduleFillDrag(); }
function employeeShiftBranchId(employeeId, requestedBranchId, existing) { if (existing?.branch_id) return Number(existing.branch_id); const branchIds = scheduleState.memberships.filter((item) => String(item.user_id) === String(employeeId)).map((item) => String(item.branch_id)).filter(Boolean); const requested = String(requestedBranchId || ""); if (requested && branchIds.includes(requested)) return Number(requested); const selected = branchIds.find((id) => scheduleState.selectedBranchIds.has(id)); return Number(selected || branchIds[0] || requestedBranchId || 0); }
async function persistShift(ctx, key, value, branchId, target = scheduleState.shifts, forceBranch = false) { const [employeeId, date] = key.split(":"); const existing = target.get(key); const body = { branch_id: employeeShiftBranchId(employeeId, branchId, forceBranch ? null : existing), start_time: value.start_time, end_time: value.end_time, breaks: value.breaks.map((item) => ({ start_time: item.start_time, end_time: item.end_time })) }; const saved = existing?.id ? await api.updateEmployeeShift(ctx.org.id, existing.id, body) : await api.createEmployeeShift(ctx.org.id, { ...body, employee_id: Number(employeeId), date }); const normalized = normalizeShift(saved); target.set(key, normalized); return normalized; }
function pageMarkup() { return `<section class="panel schedule-page" data-schedules><div class="schedule-head"><h2>Графики</h2><div class="schedule-week-nav"><button type="button" class="ghost" data-schedule-week="prev" aria-label="Предыдущая неделя">←</button><strong class="schedule-week-title">${esc(weekTitle())}</strong><button type="button" class="ghost" data-schedule-week="next" aria-label="Следующая неделя">→</button><button type="button" class="btn btn-outline-secondary" data-schedule-today>Сегодня</button></div></div>${scheduleFilters()}<div class="schedule-actions"><button type="button" class="btn btn-outline-secondary" data-schedule-copy-week>Скопировать неделю</button><small>${esc(summary())}</small></div><div data-schedule-grid-area>${scheduleGrid()}</div>${selectionBar()}</section>`; }
export async function schedules(ctx) {
  if (String(scheduleState.organizationId || "") !== String(ctx.org.id)) {
    const [branches, users, roles, memberships] = await Promise.all([api.branches(ctx.org.id), api.users(ctx.org.id, 500), api.roles(ctx.org.id), api.branchMemberships(ctx.org.id)]);
    Object.assign(scheduleState, { organizationId: ctx.org.id, weekStart: monday(), branches, users, roles, memberships, selectedBranchIds: new Set(branches.map((item) => String(item.id))), selectedUserIds: new Set(users.filter((user) => user.is_active !== false).map((user) => String(user.id))), shifts: new Map(), selectedCells: new Set(), selectionMode: false, dragSelection: { active: false, moved: false, mode: "add", startKey: null, startCell: null, visited: new Set(), suppressClick: false }, fillDrag: { active: false, sourceKey: null, sourceUserId: null, sourceDate: null, sourceShift: null, sourceUserIndex: null, sourceDateIndex: null, targetUserId: null, targetUserIndex: null, targetDate: null, targetDateIndex: null, previewKeys: new Set(), suppressClick: false }, copiedShift: null, search: "", showInactive: false });
  }
  await loadScheduleWeek(ctx);
  return pageMarkup();
}
function putModal(root, html) { root.querySelector("[data-schedule-modal]")?.remove(); root.insertAdjacentHTML("beforeend", html); }
function modal(title, body) { return `<div class="modal-backdrop" data-schedule-modal><div class="modal-card schedule-modal-card" role="dialog"><button type="button" class="modal-close" data-schedule-close aria-label="Закрыть">×</button><h3>${esc(title)}</h3>${body}</div></div>`; }
function weekActionsModal(title, body) { return `<div class="modal-backdrop" data-schedule-modal><div class="modal-card schedule-week-actions-modal" role="dialog" aria-modal="true"><div class="modal-head"><h3>${esc(title)}</h3><button type="button" class="modal-close-icon" data-schedule-close aria-label="Закрыть">×</button></div>${body}</div></div>`; }
function breaksMarkup(breaks = []) { return `<div class="schedule-breaks" data-schedule-breaks>${breaks.map((item, index) => `<div class="schedule-break-row"><input type="time" data-break-start value="${esc(item.start_time)}"><span>—</span><input type="time" data-break-end value="${esc(item.end_time)}"><button type="button" class="ghost" data-schedule-remove-break="${index}">×</button></div>`).join("")}</div>`; }
function shiftForm({ title, user, date, shift, bulk = false, keys = [] }) { const value = shift || { start_time: "10:00", end_time: "19:00", breaks: [] }; return modal(title, `<form class="schedule-shift-form" data-schedule-shift-form data-user-id="${user ? Number(user.id) : ""}" data-date="${date || ""}" data-bulk="${bulk ? "true" : "false"}" data-keys="${esc(JSON.stringify(keys))}">${user ? `<p><strong>Сотрудник:</strong> ${esc(fullName(user))}<br><strong>Дата:</strong> ${esc(dateLabel(dateFromValue(date)))}</p>` : `<p>Выбрано: ${keys.length} ячеек</p>`}<div class="schedule-time-row"><label><span>Начало</span><input type="time" name="start_time" value="${esc(value.start_time)}" required></label><span>—</span><label><span>Окончание</span><input type="time" name="end_time" value="${esc(value.end_time)}" required></label></div><div><strong>Перерывы</strong>${breaksMarkup(value.breaks)}<button type="button" class="ghost" data-schedule-add-break>+ Добавить перерыв</button></div><p data-schedule-form-message></p><div class="schedule-modal-actions">${shift && !bulk ? `<button type="button" class="ghost" data-schedule-copy="${Number(user.id)}:${date}">Копировать</button><button type="button" class="client-delete-button" data-schedule-delete="${Number(user.id)}:${date}">Удалить смену</button>` : ""}<button class="primary" type="submit">${bulk ? "Применить" : "Сохранить"}</button></div></form>`); }
function weekActionsForm(user, keys) { return weekActionsModal("Действия на неделю", `<form class="schedule-shift-form schedule-week-actions-form" data-schedule-shift-form data-bulk="true" data-keys="${esc(JSON.stringify(keys))}"><div class="schedule-week-actions-context"><strong>${esc(fullName(user))}</strong><small>${esc(weekTitle())}</small></div><div class="schedule-week-actions-time"><label><span>Начало</span><input type="time" name="start_time" value="10:00" required></label><label><span>Окончание</span><input type="time" name="end_time" value="19:00" required></label></div><div><strong>Перерывы</strong>${breaksMarkup()}<button type="button" class="ghost" data-schedule-add-break>+ Добавить перерыв</button></div><p class="schedule-week-actions-message" data-schedule-form-message></p><div class="schedule-week-actions-footer"><button type="button" class="btn btn-outline-secondary" data-schedule-close>Отмена</button><button type="submit" class="primary standard-save-button">Применить</button></div></form>`); }
function openShiftModal(root, userId, date) { const user = scheduleState.users.find((item) => String(item.id) === String(userId)); const shift = scheduleState.shifts.get(shiftKey(userId, date)); putModal(root, shiftForm({ title: shift ? "Редактирование смены" : "Добавить смену", user, date, shift })); }
function validateShift(value) { if (!value.start_time || !value.end_time || value.start_time >= value.end_time) return "Время окончания должно быть позже времени начала."; const breaks = [...value.breaks].sort((a, b) => a.start_time.localeCompare(b.start_time)); for (let index = 0; index < breaks.length; index += 1) { const item = breaks[index]; if (!item.start_time || !item.end_time || item.start_time >= item.end_time || item.start_time < value.start_time || item.end_time > value.end_time) return "Перерыв должен находиться внутри смены и иметь корректное время."; if (index && item.start_time < breaks[index - 1].end_time) return "Перерывы не должны пересекаться."; } return ""; }
function refresh(root) { resetScheduleDragSelection(); const page = root.querySelector("[data-schedules]"); if (page) page.outerHTML = pageMarkup(); }
function formValue(form) { return { start_time: new FormData(form).get("start_time"), end_time: new FormData(form).get("end_time"), breaks: [...form.querySelectorAll(".schedule-break-row")].map((row) => ({ start_time: row.querySelector("[data-break-start]").value, end_time: row.querySelector("[data-break-end]").value })) }; }
export function bindSchedules(root, ctx) {
  root.addEventListener("pointerdown", (event) => { const handle = event.target.closest("[data-schedule-fill-handle]"); if (!handle || event.button !== 0 || event.pointerType === "touch" || scheduleState.selectionMode) return; const cell = handle.closest("[data-schedule-cell]"); if (!cell) return; const key = shiftKey(cell.dataset.userId, cell.dataset.date); const shift = scheduleState.shifts.get(key); if (!shift) return; event.preventDefault(); event.stopPropagation(); resetScheduleFillDrag(); const drag = scheduleState.fillDrag; const users = availableUsers(); const dates = weekDays().map(dateValue); drag.active = true; drag.sourceKey = key; drag.sourceUserId = String(cell.dataset.userId); drag.sourceDate = cell.dataset.date; drag.sourceShift = copiedScheduleShift(shift); drag.sourceUserIndex = users.findIndex((user) => String(user.id) === drag.sourceUserId); drag.sourceDateIndex = dates.indexOf(drag.sourceDate); root.querySelector("[data-schedule-grid]")?.classList.add("is-fill-dragging"); cell.querySelector(".schedule-shift-card")?.classList.add("is-fill-source"); });
  root.addEventListener("pointerover", (event) => { const drag = scheduleState.fillDrag; if (!drag.active || event.pointerType === "touch") return; const cell = event.target.closest("[data-schedule-cell]"); if (!cell) return; const users = availableUsers(); const dates = weekDays().map(dateValue); const keys = scheduleFillRectangle(drag.sourceUserId, drag.sourceDate, cell.dataset.userId, cell.dataset.date); drag.targetUserId = String(cell.dataset.userId); drag.targetUserIndex = users.findIndex((user) => String(user.id) === drag.targetUserId); drag.targetDate = cell.dataset.date; drag.targetDateIndex = dates.indexOf(drag.targetDate); syncScheduleFillPreview(root, keys); });
  root.addEventListener("pointerdown", (event) => { const cell = event.target.closest("[data-schedule-cell]"); if (!cell || !scheduleState.selectionMode || event.button !== 0 || event.pointerType === "touch") return; const drag = scheduleState.dragSelection; drag.active = true; drag.moved = false; drag.mode = scheduleState.selectedCells.has(shiftKey(cell.dataset.userId, cell.dataset.date)) ? "remove" : "add"; drag.startKey = shiftKey(cell.dataset.userId, cell.dataset.date); drag.startCell = cell; drag.visited.clear(); drag.suppressClick = false; });
  root.addEventListener("pointerover", (event) => { const drag = scheduleState.dragSelection; if (!drag.active || event.pointerType === "touch") return; const cell = event.target.closest("[data-schedule-cell]"); if (!cell) return; const key = shiftKey(cell.dataset.userId, cell.dataset.date); if (key === drag.startKey && !drag.moved) return; if (!drag.moved) { drag.moved = true; event.preventDefault(); root.querySelector("[data-schedule-grid]")?.classList.add("is-drag-selecting"); applyScheduleDragCell(root, drag.startCell); } event.preventDefault(); applyScheduleDragCell(root, cell); });
  const finishDrag = () => { const drag = scheduleState.dragSelection; if (!drag.active) return; drag.suppressClick = drag.moved; drag.active = false; drag.moved = false; drag.startKey = null; drag.startCell = null; drag.visited.clear(); root.querySelector("[data-schedule-grid]")?.classList.remove("is-drag-selecting"); };
  const finishFillDrag = async (commit) => { const drag = scheduleState.fillDrag; if (!drag.active) return; const keys = [...drag.previewKeys]; const sourceShift = drag.sourceShift; root.querySelector("[data-schedule-grid]")?.classList.remove("is-fill-dragging"); try { if (commit && keys.length && sourceShift) { for (const key of keys) await persistShift(ctx, key, copiedScheduleShift(sourceShift), sourceShift.branch_id, scheduleState.shifts, true); await loadScheduleWeek(ctx); refresh(root); } } catch (error) { window.alert(error?.message || "Не удалось скопировать смену."); } finally { syncScheduleFillPreview(root, []); resetScheduleFillDrag(); scheduleState.fillDrag.suppressClick = true; } };
  window.addEventListener("pointerup", finishDrag);
  window.addEventListener("pointercancel", finishDrag);
  window.addEventListener("pointerup", () => { void finishFillDrag(true); });
  window.addEventListener("pointercancel", () => { void finishFillDrag(false); });
  root.addEventListener("click", async (event) => {
    if (!event.target.closest("[data-schedules], [data-schedule-modal]")) return;
    if (event.target.matches("[data-schedule-modal]") || event.target.closest("[data-schedule-close]")) { root.querySelector("[data-schedule-modal]")?.remove(); return; }
    const week = event.target.closest("[data-schedule-week]"); if (week) { resetScheduleFillDrag(); scheduleState.weekStart = addDays(scheduleState.weekStart, week.dataset.scheduleWeek === "next" ? 7 : -7); await loadScheduleWeek(ctx); refresh(root); return; }
    if (event.target.closest("[data-schedule-today]")) { resetScheduleFillDrag(); scheduleState.weekStart = monday(); await loadScheduleWeek(ctx); refresh(root); return; }
    const toggle = event.target.closest("[data-schedule-selection-toggle]"); if (toggle) { scheduleState.selectionMode = !scheduleState.selectionMode; resetScheduleDragSelection(); resetScheduleFillDrag(); if (!scheduleState.selectionMode) scheduleState.selectedCells.clear(); refresh(root); return; }
    const cell = event.target.closest("[data-schedule-cell]"); if (cell) { if (scheduleState.fillDrag.suppressClick) { scheduleState.fillDrag.suppressClick = false; return; } const key = shiftKey(cell.dataset.userId, cell.dataset.date); if (scheduleState.selectionMode) { if (scheduleState.dragSelection.suppressClick) { scheduleState.dragSelection.suppressClick = false; return; } scheduleState.selectedCells.has(key) ? scheduleState.selectedCells.delete(key) : scheduleState.selectedCells.add(key); refresh(root); } else if (event.ctrlKey && scheduleState.copiedShift && !scheduleState.shifts.has(key)) { await persistShift(ctx, key, scheduleState.copiedShift, scheduleState.copiedShift.branch_id); refresh(root); } else openShiftModal(root, cell.dataset.userId, cell.dataset.date); return; }
    if (event.target.closest("[data-schedule-unselect]")) { scheduleState.selectedCells.clear(); refresh(root); return; }
    if (event.target.closest("[data-schedule-clear]")) { if (confirm("Удалить смены в выбранных датах?")) { const items = [...scheduleState.selectedCells].filter((key) => scheduleState.shifts.has(key)).map((key) => { const [employeeId, date] = key.split(":"); return { employee_id: Number(employeeId), date }; }); if (items.length) await api.bulkDeleteEmployeeShifts(ctx.org.id, items); scheduleState.selectedCells.forEach((key) => scheduleState.shifts.delete(key)); scheduleState.selectedCells.clear(); refresh(root); } return; }
    if (event.target.closest("[data-schedule-bulk]")) { putModal(root, shiftForm({ title: "Назначить смену", bulk: true, keys: [...scheduleState.selectedCells] })); return; }
    const removeBreak = event.target.closest("[data-schedule-remove-break]"); if (removeBreak) { removeBreak.closest(".schedule-break-row")?.remove(); return; }
    if (event.target.closest("[data-schedule-add-break]")) { event.target.closest("form").querySelector("[data-schedule-breaks]").insertAdjacentHTML("beforeend", `<div class="schedule-break-row"><input type="time" data-break-start value="13:00"><span>—</span><input type="time" data-break-end value="14:00"><button type="button" class="ghost" data-schedule-remove-break>×</button></div>`); return; }
    const copy = event.target.closest("[data-schedule-copy]"); if (copy) { scheduleState.copiedShift = scheduleState.shifts.get(copy.dataset.scheduleCopy); root.querySelector("[data-schedule-modal]")?.remove(); return; }
    const deletion = event.target.closest("[data-schedule-delete]"); if (deletion) { const [, date] = deletion.dataset.scheduleDelete.split(":"); if (confirm(`Удалить смену сотрудника на ${dateLabel(dateFromValue(date))}?`)) { const shift = scheduleState.shifts.get(deletion.dataset.scheduleDelete); if (shift?.id) await api.deleteEmployeeShift(ctx.org.id, shift.id); scheduleState.shifts.delete(deletion.dataset.scheduleDelete); root.querySelector("[data-schedule-modal]")?.remove(); refresh(root); } return; }
    const weekUser = event.target.closest("[data-schedule-week-user]"); if (weekUser) { const user = scheduleState.users.find((item) => String(item.id) === String(weekUser.dataset.scheduleWeekUser)); if (!user) return; const keys = weekDays().map((date) => shiftKey(user.id, dateValue(date))); putModal(root, weekActionsForm(user, keys)); return; }
    if (event.target.closest("[data-schedule-copy-week]")) { const target = addDays(scheduleState.weekStart, 7); const keys = []; weekDays().forEach((date) => scheduleState.users.forEach((user) => { const source = scheduleState.shifts.get(shiftKey(user.id, dateValue(date))); if (source) keys.push({ key: shiftKey(user.id, dateValue(addDays(date, 7))), shift: source }); })); const targetShifts = await scheduleShiftMap(ctx, target); if (keys.length && (![...keys].some(({ key }) => targetShifts.has(key)) || confirm("В выбранной неделе уже есть смены. Перезаписать существующие?"))) { await Promise.all(keys.map(({ key, shift }) => persistShift(ctx, key, shift, shift.branch_id, targetShifts))); scheduleState.weekStart = target; scheduleState.shifts = targetShifts; refresh(root); } return; }
  });
  root.addEventListener("change", (event) => {
    const option = event.target.closest("[data-schedule-filter-option]"); const all = event.target.closest("[data-schedule-filter-all]");
    if (option || all) { resetScheduleFillDrag(); const type = (option || all).dataset.scheduleFilterOption || (option || all).dataset.scheduleFilterAll; const items = type === "branch" ? scheduleState.branches : scheduleState.users.filter((user) => scheduleState.showInactive || user.is_active !== false); const selected = type === "branch" ? scheduleState.selectedBranchIds : scheduleState.selectedUserIds; if (all) { selected.clear(); if (all.checked) items.forEach((item) => selected.add(String(item.id))); } else { option.checked ? selected.add(String(option.value)) : selected.delete(String(option.value)); } if (type === "branch") { const visible = availableUsers().map((user) => String(user.id)); scheduleState.selectedUserIds = new Set([...scheduleState.selectedUserIds].filter((id) => visible.includes(id))); } refresh(root); return; }
    if (event.target.matches("[data-schedule-show-inactive]")) { resetScheduleFillDrag(); scheduleState.showInactive = event.target.checked; if (scheduleState.showInactive) scheduleState.users.forEach((user) => scheduleState.selectedUserIds.add(String(user.id))); refresh(root); }
  });
  root.addEventListener("input", (event) => { if (event.target.matches("[data-schedule-search]")) { resetScheduleDragSelection(); resetScheduleFillDrag(); scheduleState.search = event.target.value; root.querySelector("[data-schedule-grid-area]").innerHTML = scheduleGrid(); } });
  root.addEventListener("submit", async (event) => { const form = event.target; if (!form.matches("[data-schedule-shift-form]")) return; event.preventDefault(); const value = formValue(form); const error = validateShift(value); const message = form.querySelector("[data-schedule-form-message]"); if (error) { message.textContent = error; return; } const keys = form.dataset.bulk === "true" ? JSON.parse(form.dataset.keys || "[]") : [shiftKey(form.dataset.userId, form.dataset.date)]; const existing = keys.filter((key) => scheduleState.shifts.has(key)).length; if (form.dataset.bulk === "true" && existing && !confirm(`В выбранных ячейках уже есть ${existing} смены. Заменить их?`)) return; const branchId = [...scheduleState.selectedBranchIds][0] || 0; const submit = form.querySelector('[type="submit"]'); if (submit) submit.disabled = true; try { await Promise.all(keys.map((key) => persistShift(ctx, key, value, branchId))); scheduleState.selectedCells.clear(); root.querySelector("[data-schedule-modal]")?.remove(); refresh(root); } catch (saveError) { message.textContent = saveError.message; if (submit) submit.disabled = false; } });
}
